#debug模式，true输出控制台日志，false只输出文件日志.生产环境需要关闭debug，rbatis也需移除"debug_mode"
debug: true
#名称
server_name: "home_cloud"
#server 地址
server_url: "0.0.0.0:9000"
#主数据库地址
primary_database_url: "mysql://root:root@10.203.1.204:3306/primary"
#辅助业务数据库地址
business_database_url: "mysql://root:root@10.203.1.204:3306/business"
#财政相关数据库地址
financial_database_url: "mysql://root:root@10.203.1.204:3306/financial"
#逻辑删除字段
logic_column: "status"
#未删除时的状态
logic_un_deleted: 0
#删除后的状态
logic_deleted: 1
#日志文件存放目录
log_dir: "target/logs/"
#日志分割尺寸-单位KB,MB,GB
log_temp_size: "100MB"
#日志打包格式可选“”（空-不压缩）“gzip”（gz压缩包）“zip”（zip压缩包）“lz4”（lz4压缩包（非常快））
log_pack_compress: "zip"
#日志滚动保留-保留全部: All,按时间保留(秒): KeepTime(i64),按版本保留: KeepNum(i64)
log_rolling_type: "KeepNum(20)"
#日志等级-info,error,warn,debug,trace
log_level: "info"
#JwtToken秘钥
jwt_secret: "home_cloud"
#登陆失败拒绝策略，重试次数限制(0次无限制)
login_fail_retry: 3
#登陆失败重试次数限制超过后提示的等待时间（秒）
login_fail_retry_wait_sec: 30
#数据目录
data_dir: /Users/saya/warehouse

#接口白名单（免登陆直接访问）
white_list_api:
 - "/login"
 - "/logout"
 - "/warehouse/picture/*"
